import { StyleSheet } from "react-native";

import type { Theme } from "../../theme/theme";

export function makeStyles(theme: Theme) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.homeBg,
    },
    rootDark: {
      flex: 1,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingTop: 56,
      paddingBottom: 40,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingBottom: 12,
    },
    headerLeft: { flex: 1 },
    periodLabel: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      letterSpacing: 0.5,
    },
    headerStatRow: {
      flexDirection: "row",
      alignItems: "baseline",
      marginTop: 2,
    },
    headerStatNum: {
      color: theme.textPrimary,
      fontSize: 28,
      fontWeight: "800",
    },
    headerStatUnit: {
      color: theme.textPrimary,
      fontSize: 14,
      fontWeight: "600",
    },
    headerStatDot: {
      color: theme.textMuted,
      fontSize: 18,
    },
    iconBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.cardBg,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    iconBtnPressed: { backgroundColor: theme.tabRowBg },
    iconBtnLarge: {
      width: 44,
      height: 44,
      borderRadius: 22,
    },
    headerRightSpacer: {
      width: 44,
      height: 44,
    },
    headerFloatingBtn: {
      position: "absolute",
      top: 56,
      right: 20,
      zIndex: 10,
    },
    iconBtnText: {
      color: theme.textPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    iconBtnTextLarge: {
      fontSize: 22,
    },
    tabRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 8,
      gap: 12,
    },
    tabPills: {
      flexDirection: "row",
      backgroundColor: theme.tabRowBg,
      borderRadius: 999,
      padding: 4,
      gap: 4,
    },
    tab: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 999,
    },
    tabActive: {
      backgroundColor: theme.cardBg,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 1 },
      shadowRadius: 2,
      elevation: 1,
    },
    tabText: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: "600",
    },
    tabTextActive: {
      color: theme.textPrimary,
      fontWeight: "700",
    },
    syncBar: {
      marginHorizontal: 20,
      marginTop: 4,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: theme.cardBg,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.cardBorder,
    },
    syncText: { color: theme.accentSoftText, fontSize: 12, fontWeight: "600" },
    mapWrap: {
      marginTop: 8,
      marginBottom: 16,
      paddingHorizontal: 0,
      paddingVertical: 12,
      backgroundColor: theme.cardBg,
      position: "relative",
    },
    mapFloatingBtn: {
      position: "absolute",
      left: 12,
      bottom: 12,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.cardBg,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 6,
      elevation: 3,
    },
    mapFloatingBtnPressed: {
      backgroundColor: theme.tabRowBg,
    },
    mapFloatingBtnIcon: {
      color: theme.textPrimary,
      fontSize: 14,
      fontWeight: "700",
    },
    statsRow: {
      flexDirection: "row",
      paddingHorizontal: 20,
      gap: 12,
      marginBottom: 24,
    },
    miniCard: {
      flex: 1,
      backgroundColor: theme.cardBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      padding: 12,
      minHeight: 140,
    },
    miniCardPressed: {
      backgroundColor: theme.tabRowBg,
    },
    miniBadge: {
      alignSelf: "flex-start",
      backgroundColor: theme.tabRowBg,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    miniBadgeText: {
      color: theme.textPrimary,
      fontSize: 11,
      fontWeight: "700",
    },
    miniDotsArea: {
      flex: 1,
      alignItems: "stretch",
      justifyContent: "center",
      paddingVertical: 8,
    },
    miniTitle: {
      color: theme.textPrimary,
      fontSize: 13,
      fontWeight: "700",
    },
    miniSub: {
      color: theme.textSecondary,
      fontSize: 11,
      marginTop: 2,
    },
    statCard: {
      flex: 1.5,
      backgroundColor: theme.cardBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      padding: 14,
      minHeight: 140,
      justifyContent: "space-between",
    },
    statHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    statTitle: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: "600",
    },
    statTier: {
      color: theme.accent,
      fontSize: 12,
      fontWeight: "700",
      maxWidth: 180,
      flexShrink: 1,
    },
    statTierPrestige: {
      color: theme.accentSoftText,
      backgroundColor: theme.accentSoftBg,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      overflow: "hidden",
    },
    statBigRow: {
      flexDirection: "row",
      alignItems: "baseline",
      marginTop: 4,
    },
    statBigNum: {
      color: theme.textPrimary,
      fontSize: 30,
      fontWeight: "800",
    },
    statBigDenom: {
      color: theme.textMuted,
      fontSize: 14,
      fontWeight: "600",
    },
    statBigPercent: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: "700",
    },
    progressTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.tabRowBg,
      overflow: "hidden",
      marginTop: 8,
    },
    progressFill: {
      height: "100%",
      borderRadius: 3,
      backgroundColor: theme.accent,
    },
    statFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 8,
    },
    statFooterLabel: {
      color: theme.textSecondary,
      fontSize: 11,
    },
    statFooterStrong: {
      color: theme.textPrimary,
      fontWeight: "700",
    },
    statFooterAccent: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: "700",
    },
    recentHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    recentHeaderLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    recentAddBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.cardBg,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    recentAddBtnPressed: {
      backgroundColor: theme.tabRowBg,
    },
    recentAddIcon: {
      color: theme.textPrimary,
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 20,
      marginTop: -2,
    },
    sectionTitle: {
      color: theme.textPrimary,
      fontSize: 17,
      fontWeight: "800",
    },
    allLink: {
      color: theme.accent,
      fontSize: 13,
      fontWeight: "700",
    },
    rowSep: { height: 1, backgroundColor: theme.cardBorder, marginLeft: 20 },
    recentRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingVertical: 12,
      gap: 12,
    },
    flagBox: {
      width: 46,
      height: 46,
      borderRadius: 12,
      backgroundColor: theme.flagBoxBg,
      alignItems: "center",
      justifyContent: "center",
    },
    flagText: { fontSize: 26 },
    recentMain: { flex: 1 },
    recentTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    recentName: {
      color: theme.textPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    recentCode: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: "600",
    },
    recentBadge: {
      marginLeft: 6,
      backgroundColor: theme.accentSoftBg,
      borderRadius: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    recentBadgeText: {
      color: theme.accentSoftText,
      fontSize: 10,
      fontWeight: "800",
    },
    recentDate: {
      color: theme.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    chev: {
      color: theme.textMuted,
      fontSize: 22,
      fontWeight: "400",
    },
    emptyWrap: {
      paddingHorizontal: 20,
      paddingVertical: 24,
    },
    emptyText: {
      color: theme.textSecondary,
      fontSize: 13,
      textAlign: "center",
    },
    allCountriesBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 32,
      paddingVertical: 16,
      paddingHorizontal: 18,
      backgroundColor: theme.cardBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.cardBorder,
    },
    allCountriesBtnPressed: {
      backgroundColor: theme.rowPressedBg,
    },
    allCountriesIcon: {
      fontSize: 20,
    },
    allCountriesText: {
      flex: 1,
      color: theme.textPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    allCountriesChev: {
      color: theme.textMuted,
      fontSize: 22,
      fontWeight: "400",
    },
  });
}

export type MainScreenStyles = ReturnType<typeof makeStyles>;
