-- 여행 상식 퀴즈 100문제 시드 (10개 locale).
-- 구조: 한 row = 한 질문. translations jsonb에 {locale: {q, c}} 형태로 모든 언어 통합 보관.
-- 적용 흐름:
--   1) ko 번역과 함께 100문제 INSERT (id 1~100, 작성 순서 = 아래 list 순서).
--   2) en / ja / zh-CN / zh-TW / de / es / fr / it / ru — 각각 100문제의 (q,c)를 id 매칭으로 UPDATE 병합.
-- 새 문제 추가 시: 위 INSERT 블록에 1줄(전체 locale 번역 포함) 추가, UPDATE 블록도 같은 위치에 1줄씩 추가.
-- 새 언어 추가 시: 100문제 전체에 UPDATE 블록 1개를 새로 작성해서 끝에 붙인다.

-- ============================================================
-- 1) INSERT: 100문제 base row (ko 번역만 포함)
-- ============================================================
insert into public.travel_trivia_questions (category, difficulty, correct_index, translations) values
('landmark', 1, 0, $${"ko":{"q":"자유의 여신상이 위치한 도시는?","c":["뉴욕","워싱턴 D.C.","보스턴","로스앤젤레스"]}}$$::jsonb),
('landmark', 1, 1, $${"ko":{"q":"에펠탑이 있는 도시는?","c":["런던","파리","로마","베를린"]}}$$::jsonb),
('capital', 1, 2, $${"ko":{"q":"일본의 수도는?","c":["오사카","교토","도쿄","후쿠오카"]}}$$::jsonb),
('capital', 1, 2, $${"ko":{"q":"영국의 수도는?","c":["에든버러","더블린","런던","카디프"]}}$$::jsonb),
('landmark', 1, 2, $${"ko":{"q":"만리장성이 있는 나라는?","c":["일본","한국","중국","베트남"]}}$$::jsonb),
('landmark', 1, 0, $${"ko":{"q":"시드니 오페라하우스가 있는 나라는?","c":["호주","뉴질랜드","영국","캐나다"]}}$$::jsonb),
('landmark', 1, 1, $${"ko":{"q":"콜로세움이 있는 도시는?","c":["밀라노","로마","베네치아","피렌체"]}}$$::jsonb),
('landmark', 1, 1, $${"ko":{"q":"거대한 피라미드와 스핑크스로 가장 유명한 나라는?","c":["멕시코","이집트","페루","그리스"]}}$$::jsonb),
('capital', 1, 0, $${"ko":{"q":"태국의 수도는?","c":["방콕","치앙마이","푸켓","파타야"]}}$$::jsonb),
('capital', 1, 2, $${"ko":{"q":"미국의 수도는?","c":["뉴욕","로스앤젤레스","워싱턴 D.C.","시카고"]}}$$::jsonb),
('flag', 1, 1, $${"ko":{"q":"캐나다 국기 한가운데에 그려진 잎은?","c":["참나무 잎","단풍잎","은행잎","소나무 잎"]}}$$::jsonb),
('geography', 1, 3, $${"ko":{"q":"다음 중 섬나라가 아닌 곳은?","c":["일본","뉴질랜드","영국","베트남"]}}$$::jsonb),
('food', 1, 3, $${"ko":{"q":"김치와 비빔밥의 본고장인 나라는?","c":["중국","일본","베트남","한국"]}}$$::jsonb),
('food', 1, 1, $${"ko":{"q":"스시(Sushi)는 어느 나라의 대표 음식인가요?","c":["중국","일본","한국","베트남"]}}$$::jsonb),
('food', 1, 1, $${"ko":{"q":"피자(Pizza)의 본고장으로 가장 잘 알려진 나라는?","c":["그리스","이탈리아","프랑스","스페인"]}}$$::jsonb),
('food', 1, 1, $${"ko":{"q":"바게트(Baguette)로 유명한 나라는?","c":["이탈리아","프랑스","독일","영국"]}}$$::jsonb),
('food', 1, 1, $${"ko":{"q":"파스타(Pasta)의 원조 국가는?","c":["그리스","이탈리아","스페인","포르투갈"]}}$$::jsonb),
('food', 1, 1, $${"ko":{"q":"커리(Curry)와 가장 깊은 관련이 있는 나라는?","c":["태국","인도","베트남","일본"]}}$$::jsonb),
('language', 1, 3, $${"ko":{"q":"다음 중 공용어가 영어가 아닌 나라는?","c":["캐나다","호주","뉴질랜드","브라질"]}}$$::jsonb),
('language', 1, 2, $${"ko":{"q":"다음 중 공용어가 스페인어가 아닌 나라는?","c":["멕시코","아르헨티나","브라질","칠레"]}}$$::jsonb),
('language', 1, 1, $${"ko":{"q":"다음 중 프랑스어를 공용어로 쓰는 나라는?","c":["네덜란드","프랑스","폴란드","헝가리"]}}$$::jsonb),
('language', 1, 3, $${"ko":{"q":"다음 중 공용어가 독일어가 아닌 나라는?","c":["독일","오스트리아","스위스","폴란드"]}}$$::jsonb),
('history', 1, 3, $${"ko":{"q":"세계 4대 문명에 속하지 않는 곳은?","c":["메소포타미아","이집트","인더스","그리스"]}}$$::jsonb),
('geography', 1, 2, $${"ko":{"q":"다음 중 유럽에 있는 나라는?","c":["태국","베트남","그리스","칠레"]}}$$::jsonb),
('geography', 1, 1, $${"ko":{"q":"다음 중 아프리카 대륙에 있는 나라는?","c":["이란","이집트","인도","인도네시아"]}}$$::jsonb),
('geography', 1, 1, $${"ko":{"q":"다음 중 남미에 있는 나라는?","c":["멕시코","브라질","쿠바","자메이카"]}}$$::jsonb),
('culture', 1, 1, $${"ko":{"q":"캥거루는 어느 나라를 상징하는 동물인가요?","c":["뉴질랜드","호주","남아공","브라질"]}}$$::jsonb),
('culture', 1, 1, $${"ko":{"q":"판다는 어느 나라를 상징하는 동물인가요?","c":["한국","중국","일본","태국"]}}$$::jsonb),
('culture', 1, 0, $${"ko":{"q":"리우 카니발로 유명한 나라는?","c":["브라질","아르헨티나","칠레","페루"]}}$$::jsonb),
('currency', 1, 1, $${"ko":{"q":"영국의 통화 단위는?","c":["유로","파운드","달러","프랑"]}}$$::jsonb),
('currency', 1, 2, $${"ko":{"q":"미국의 통화 단위는?","c":["파운드","유로","달러","엔"]}}$$::jsonb),
('currency', 1, 0, $${"ko":{"q":"일본의 통화 단위는?","c":["엔","위안","원","동"]}}$$::jsonb),
('culture', 1, 2, $${"ko":{"q":"FIFA 월드컵 우승 횟수가 가장 많은 나라는?","c":["독일","이탈리아","브라질","아르헨티나"]}}$$::jsonb),
('geography', 1, 3, $${"ko":{"q":"다음 중 알프스 산맥이 지나지 않는 나라는?","c":["스위스","이탈리아","오스트리아","네덜란드"]}}$$::jsonb),
('landmark', 1, 1, $${"ko":{"q":"빅벤(Big Ben)이 있는 도시는?","c":["파리","런던","베를린","마드리드"]}}$$::jsonb),
('capital', 2, 2, $${"ko":{"q":"호주의 수도는?","c":["시드니","멜버른","캔버라","브리즈번"]}}$$::jsonb),
('capital', 2, 2, $${"ko":{"q":"캐나다의 수도는?","c":["토론토","밴쿠버","오타와","몬트리올"]}}$$::jsonb),
('capital', 2, 2, $${"ko":{"q":"브라질의 수도는?","c":["상파울루","리우데자네이루","브라질리아","살바도르"]}}$$::jsonb),
('capital', 2, 1, $${"ko":{"q":"터키(튀르키예)의 수도는?","c":["이스탄불","앙카라","이즈미르","안탈리아"]}}$$::jsonb),
('capital', 2, 2, $${"ko":{"q":"남아프리카공화국의 행정 수도는?","c":["요하네스버그","케이프타운","프리토리아","더반"]}}$$::jsonb),
('capital', 2, 0, $${"ko":{"q":"노르웨이의 수도는?","c":["오슬로","베르겐","코펜하겐","헬싱키"]}}$$::jsonb),
('landmark', 2, 2, $${"ko":{"q":"타지마할이 있는 인도 도시는?","c":["델리","뭄바이","아그라","자이푸르"]}}$$::jsonb),
('landmark', 2, 1, $${"ko":{"q":"영화 인디아나 존스에 등장한 페트라(Petra) 유적이 있는 나라는?","c":["이집트","요르단","이스라엘","터키"]}}$$::jsonb),
('landmark', 2, 1, $${"ko":{"q":"잉카 문명의 공중도시 마추픽추가 있는 나라는?","c":["멕시코","페루","칠레","볼리비아"]}}$$::jsonb),
('landmark', 2, 2, $${"ko":{"q":"앙코르 와트가 있는 나라는?","c":["태국","베트남","캄보디아","라오스"]}}$$::jsonb),
('language', 2, 2, $${"ko":{"q":"다음 중 영어가 공용어가 아닌 나라는?","c":["싱가포르","필리핀","인도네시아","인도"]}}$$::jsonb),
('flag', 2, 0, $${"ko":{"q":"국기에 별과 초승달이 함께 그려진 나라는?","c":["터키","일본","한국","그리스"]}}$$::jsonb),
('flag', 2, 0, $${"ko":{"q":"국기에 붉은 태양 원이 그려진 나라는?","c":["일본","영국","미국","독일"]}}$$::jsonb),
('flag', 2, 0, $${"ko":{"q":"러시아 국기의 색상 조합으로 옳은 것은?","c":["백·청·적","적·황·청","흑·황·적","청·황·적"]}}$$::jsonb),
('currency', 2, 0, $${"ko":{"q":"칠레의 통화 단위는?","c":["페소","헤알","솔","볼리바르"]}}$$::jsonb),
('currency', 2, 0, $${"ko":{"q":"인도의 통화 단위는?","c":["루피","디나르","위안","페소"]}}$$::jsonb),
('currency', 2, 0, $${"ko":{"q":"베트남의 통화 단위는?","c":["동(VND)","바트","페소","루피"]}}$$::jsonb),
('currency', 2, 1, $${"ko":{"q":"스위스의 통화 단위는?","c":["유로","프랑(CHF)","마르크","크로네"]}}$$::jsonb),
('food', 2, 1, $${"ko":{"q":"파에야(Paella)가 유래한 나라는?","c":["이탈리아","스페인","포르투갈","멕시코"]}}$$::jsonb),
('food', 2, 2, $${"ko":{"q":"쌀국수(Pho)로 가장 유명한 나라는?","c":["중국","태국","베트남","라오스"]}}$$::jsonb),
('food', 2, 0, $${"ko":{"q":"딤섬(Dim Sum) 문화가 가장 발달한 도시는?","c":["홍콩","도쿄","서울","싱가포르"]}}$$::jsonb),
('religion', 2, 1, $${"ko":{"q":"힌두교 신자가 가장 많은 나라는?","c":["태국","인도","인도네시아","네팔"]}}$$::jsonb),
('religion', 2, 1, $${"ko":{"q":"사우디아라비아에서 가장 많은 사람이 믿는 종교는?","c":["불교","이슬람교","기독교","힌두교"]}}$$::jsonb),
('religion', 2, 1, $${"ko":{"q":"바티칸 시국의 국교는?","c":["정교회","가톨릭","개신교","이슬람교"]}}$$::jsonb),
('religion', 2, 0, $${"ko":{"q":"부탄에서 가장 많은 사람이 믿는 종교는?","c":["불교","힌두교","이슬람교","시크교"]}}$$::jsonb),
('geography', 2, 2, $${"ko":{"q":"아프리카에서 인구가 가장 많은 나라는?","c":["이집트","남아프리카공화국","나이지리아","케냐"]}}$$::jsonb),
('geography', 2, 3, $${"ko":{"q":"다음 중 북유럽 5개국(Nordic)에 속하지 않는 나라는?","c":["노르웨이","스웨덴","핀란드","에스토니아"]}}$$::jsonb),
('geography', 2, 1, $${"ko":{"q":"사하라 사막은 어느 대륙에 있나요?","c":["아시아","아프리카","호주","남미"]}}$$::jsonb),
('geography', 2, 1, $${"ko":{"q":"아마존 강이 흐르는 대륙은?","c":["북미","남미","아프리카","아시아"]}}$$::jsonb),
('geography', 2, 1, $${"ko":{"q":"사해(Dead Sea)와 국경을 접한 두 나라는?","c":["이집트-수단","이스라엘-요르단","사우디-이라크","시리아-터키"]}}$$::jsonb),
('geography', 2, 2, $${"ko":{"q":"갈라파고스 제도가 속한 나라는?","c":["페루","칠레","에콰도르","콜롬비아"]}}$$::jsonb),
('history', 2, 3, $${"ko":{"q":"다음 중 바이킹의 후예 이미지와 가장 거리가 먼 나라는?","c":["노르웨이","스웨덴","덴마크","폴란드"]}}$$::jsonb),
('history', 2, 1, $${"ko":{"q":"1986년 체르노빌 원전 사고가 일어난 현재의 국가는?","c":["러시아","우크라이나","벨라루스","폴란드"]}}$$::jsonb),
('history', 2, 0, $${"ko":{"q":"베를린 장벽이 있었던 나라는?","c":["독일","폴란드","헝가리","체코"]}}$$::jsonb),
('transport', 2, 3, $${"ko":{"q":"다음 중 차량이 좌측통행을 하지 않는 나라는?","c":["일본","영국","호주","독일"]}}$$::jsonb),
('currency', 3, 0, $${"ko":{"q":"EU 회원국이지만 유로(EUR)를 쓰지 않는 나라는?","c":["스웨덴","스페인","슬로베니아","슬로바키아"]}}$$::jsonb),
('geography', 3, 3, $${"ko":{"q":"다음 중 적도(Equator)가 지나가지 않는 나라는?","c":["에콰도르","케냐","인도네시아","페루"]}}$$::jsonb),
('geography', 3, 0, $${"ko":{"q":"두 대륙(유럽-아시아)에 걸쳐 있는 도시는?","c":["이스탄불","모스크바","카이로","아테네"]}}$$::jsonb),
('geography', 3, 2, $${"ko":{"q":"국토 면적이 세계에서 가장 작은 나라는?","c":["모나코","산마리노","바티칸시국","리히텐슈타인"]}}$$::jsonb),
('geography', 3, 1, $${"ko":{"q":"에베레스트 산이 국경을 이루는 두 나라는?","c":["중국-인도","중국-네팔","인도-네팔","중국-부탄"]}}$$::jsonb),
('geography', 3, 1, $${"ko":{"q":"2024년 기준 인구가 가장 많은 나라는?","c":["중국","인도","미국","인도네시아"]}}$$::jsonb),
('culture', 3, 0, $${"ko":{"q":"1인당 GDP가 매우 높은 것으로 유명한 유럽 소국은?","c":["룩셈부르크","한국","일본","프랑스"]}}$$::jsonb),
('language', 3, 3, $${"ko":{"q":"다음 중 한자(Hanzi)를 공식 문자로 쓰지 않는 나라는?","c":["중국","대만","일본","베트남"]}}$$::jsonb),
('language', 3, 2, $${"ko":{"q":"키릴 문자(Cyrillic)를 공식 문자로 쓰는 나라는?","c":["폴란드","체코","러시아","헝가리"]}}$$::jsonb),
('language', 3, 1, $${"ko":{"q":"다음 중 공용어가 아랍어가 아닌 나라는?","c":["이집트","이란","사우디아라비아","모로코"]}}$$::jsonb),
('culture', 3, 3, $${"ko":{"q":"다음 중 입헌군주국이 아닌 나라는?","c":["영국","일본","스웨덴","독일"]}}$$::jsonb),
('history', 3, 2, $${"ko":{"q":"다음 중 NATO 회원국이 아닌 나라는?","c":["노르웨이","폴란드","스위스","캐나다"]}}$$::jsonb),
('history', 3, 2, $${"ko":{"q":"다음 중 OPEC 회원국이 아닌 나라는?","c":["사우디아라비아","이란","러시아","베네수엘라"]}}$$::jsonb),
('nature', 3, 3, $${"ko":{"q":"오로라(북극광) 관측에 적합하지 않은 곳은?","c":["아이슬란드","핀란드","캐나다","멕시코"]}}$$::jsonb),
('nature', 3, 0, $${"ko":{"q":"바오바브나무로 유명한 섬나라는?","c":["마다가스카르","모리셔스","세이셸","코모로"]}}$$::jsonb),
('flag', 3, 0, $${"ko":{"q":"국기 한가운데에 아랍어 문구(샤하다)가 적혀 있는 나라는?","c":["사우디아라비아","이란","이라크","이집트"]}}$$::jsonb),
('geography', 3, 0, $${"ko":{"q":"한 국가 안에 시간대(타임존)가 가장 많이 있는 나라는?","c":["러시아","미국","캐나다","호주"]}}$$::jsonb),
('geography', 3, 2, $${"ko":{"q":"두바이(Dubai)가 속한 나라는?","c":["사우디아라비아","카타르","아랍에미리트","쿠웨이트"]}}$$::jsonb),
('culture', 3, 1, $${"ko":{"q":"에어버스(Airbus) 본사가 위치한 나라는?","c":["독일","프랑스","영국","스페인"]}}$$::jsonb),
('geography', 3, 1, $${"ko":{"q":"국제 표준시(UTC 0)의 기준 자오선이 지나가는 도시는?","c":["파리","런던","베를린","리스본"]}}$$::jsonb),
('history', 3, 0, $${"ko":{"q":"NATO 본부가 있는 도시는?","c":["브뤼셀","파리","런던","워싱턴 D.C."]}}$$::jsonb),
('history', 3, 1, $${"ko":{"q":"UN(국제연합) 본부가 있는 도시는?","c":["워싱턴 D.C.","뉴욕","제네바","빈"]}}$$::jsonb),
('geography', 3, 2, $${"ko":{"q":"다음 중 카리브해 섬나라가 아닌 곳은?","c":["쿠바","자메이카","코스타리카","도미니카공화국"]}}$$::jsonb),
('geography', 3, 3, $${"ko":{"q":"다음 중 발칸 반도에 위치하지 않은 나라는?","c":["세르비아","크로아티아","알바니아","헝가리"]}}$$::jsonb),
('culture', 3, 1, $${"ko":{"q":"안달루시아(Andalucia) 지방이 있는 나라는?","c":["이탈리아","스페인","포르투갈","그리스"]}}$$::jsonb),
('nature', 3, 2, $${"ko":{"q":"북유럽에서 오로라 관측이 가장 어려운 시기는?","c":["12월","1월","6월","11월"]}}$$::jsonb),
('geography', 3, 0, $${"ko":{"q":"다음 중 바다와 접하지 않은(내륙국) 나라는?","c":["오스트리아","이탈리아","크로아티아","슬로베니아"]}}$$::jsonb),
('history', 3, 2, $${"ko":{"q":"다음 중 셰겐(Schengen) 협정 구역에 속하지 않는 나라는?","c":["독일","프랑스","아일랜드","스페인"]}}$$::jsonb),
('geography', 3, 0, $${"ko":{"q":"세계에서 가장 긴 강으로 가장 널리 알려진 곳은?","c":["나일강","아마존강","양쯔강","미시시피강"]}}$$::jsonb),
('geography', 3, 1, $${"ko":{"q":"동남아시아의 대표적인 도시국가(City-state)는?","c":["태국","싱가포르","말레이시아","인도네시아"]}}$$::jsonb);

-- ============================================================
-- 2) UPDATE: en — id 1..100 순서로 매핑
-- ============================================================
with d(i,t) as (values
  (1, $${"q":"In which city is the Statue of Liberty?","c":["New York","Washington D.C.","Boston","Los Angeles"]}$$::jsonb),
  (2, $${"q":"In which city is the Eiffel Tower?","c":["London","Paris","Rome","Berlin"]}$$::jsonb),
  (3, $${"q":"What is the capital of Japan?","c":["Osaka","Kyoto","Tokyo","Fukuoka"]}$$::jsonb),
  (4, $${"q":"What is the capital of the United Kingdom?","c":["Edinburgh","Dublin","London","Cardiff"]}$$::jsonb),
  (5, $${"q":"In which country is the Great Wall?","c":["Japan","Korea","China","Vietnam"]}$$::jsonb),
  (6, $${"q":"In which country is the Sydney Opera House?","c":["Australia","New Zealand","UK","Canada"]}$$::jsonb),
  (7, $${"q":"In which city is the Colosseum?","c":["Milan","Rome","Venice","Florence"]}$$::jsonb),
  (8, $${"q":"Which country is most famous for the Great Pyramids and the Sphinx?","c":["Mexico","Egypt","Peru","Greece"]}$$::jsonb),
  (9, $${"q":"What is the capital of Thailand?","c":["Bangkok","Chiang Mai","Phuket","Pattaya"]}$$::jsonb),
  (10, $${"q":"What is the capital of the United States?","c":["New York","Los Angeles","Washington D.C.","Chicago"]}$$::jsonb),
  (11, $${"q":"What leaf is shown in the centre of the Canadian flag?","c":["Oak leaf","Maple leaf","Ginkgo leaf","Pine needle"]}$$::jsonb),
  (12, $${"q":"Which of the following is NOT an island nation?","c":["Japan","New Zealand","UK","Vietnam"]}$$::jsonb),
  (13, $${"q":"Kimchi and bibimbap are signature dishes of which country?","c":["China","Japan","Vietnam","Korea"]}$$::jsonb),
  (14, $${"q":"Sushi originates from which country?","c":["China","Japan","Korea","Vietnam"]}$$::jsonb),
  (15, $${"q":"Pizza is most famously associated with which country?","c":["Greece","Italy","France","Spain"]}$$::jsonb),
  (16, $${"q":"The baguette is most famously associated with which country?","c":["Italy","France","Germany","UK"]}$$::jsonb),
  (17, $${"q":"Pasta originates from which country?","c":["Greece","Italy","Spain","Portugal"]}$$::jsonb),
  (18, $${"q":"Curry is most strongly associated with which country?","c":["Thailand","India","Vietnam","Japan"]}$$::jsonb),
  (19, $${"q":"In which of the following countries is English NOT a primary language?","c":["Canada","Australia","New Zealand","Brazil"]}$$::jsonb),
  (20, $${"q":"In which of the following countries is Spanish NOT the main language?","c":["Mexico","Argentina","Brazil","Chile"]}$$::jsonb),
  (21, $${"q":"In which of the following countries is French an official language?","c":["Netherlands","France","Poland","Hungary"]}$$::jsonb),
  (22, $${"q":"In which country is German NOT an official language?","c":["Germany","Austria","Switzerland","Poland"]}$$::jsonb),
  (23, $${"q":"Which is NOT one of the four ancient cradles of civilisation?","c":["Mesopotamia","Egypt","Indus","Greece"]}$$::jsonb),
  (24, $${"q":"Which of the following is a country in Europe?","c":["Thailand","Vietnam","Greece","Chile"]}$$::jsonb),
  (25, $${"q":"Which of the following is a country in Africa?","c":["Iran","Egypt","India","Indonesia"]}$$::jsonb),
  (26, $${"q":"Which of the following is a country in South America?","c":["Mexico","Brazil","Cuba","Jamaica"]}$$::jsonb),
  (27, $${"q":"The kangaroo is a symbolic animal of which country?","c":["New Zealand","Australia","South Africa","Brazil"]}$$::jsonb),
  (28, $${"q":"The giant panda is a symbolic animal of which country?","c":["Korea","China","Japan","Thailand"]}$$::jsonb),
  (29, $${"q":"The Rio Carnival is famously held in which country?","c":["Brazil","Argentina","Chile","Peru"]}$$::jsonb),
  (30, $${"q":"What is the currency of the United Kingdom?","c":["Euro","Pound","Dollar","Franc"]}$$::jsonb),
  (31, $${"q":"What is the currency of the United States?","c":["Pound","Euro","Dollar","Yen"]}$$::jsonb),
  (32, $${"q":"What is the currency of Japan?","c":["Yen","Yuan","Won","Dong"]}$$::jsonb),
  (33, $${"q":"Which country has won the most FIFA World Cup titles?","c":["Germany","Italy","Brazil","Argentina"]}$$::jsonb),
  (34, $${"q":"Through which of the following countries do the Alps NOT pass?","c":["Switzerland","Italy","Austria","Netherlands"]}$$::jsonb),
  (35, $${"q":"In which city is Big Ben?","c":["Paris","London","Berlin","Madrid"]}$$::jsonb),
  (36, $${"q":"What is the capital of Australia?","c":["Sydney","Melbourne","Canberra","Brisbane"]}$$::jsonb),
  (37, $${"q":"What is the capital of Canada?","c":["Toronto","Vancouver","Ottawa","Montreal"]}$$::jsonb),
  (38, $${"q":"What is the capital of Brazil?","c":["Sao Paulo","Rio de Janeiro","Brasilia","Salvador"]}$$::jsonb),
  (39, $${"q":"What is the capital of Turkiye (Turkey)?","c":["Istanbul","Ankara","Izmir","Antalya"]}$$::jsonb),
  (40, $${"q":"What is the administrative capital of South Africa?","c":["Johannesburg","Cape Town","Pretoria","Durban"]}$$::jsonb),
  (41, $${"q":"What is the capital of Norway?","c":["Oslo","Bergen","Copenhagen","Helsinki"]}$$::jsonb),
  (42, $${"q":"In which Indian city is the Taj Mahal?","c":["Delhi","Mumbai","Agra","Jaipur"]}$$::jsonb),
  (43, $${"q":"In which country are the ruins of Petra (seen in Indiana Jones)?","c":["Egypt","Jordan","Israel","Turkiye"]}$$::jsonb),
  (44, $${"q":"In which country is Machu Picchu, the Inca citadel?","c":["Mexico","Peru","Chile","Bolivia"]}$$::jsonb),
  (45, $${"q":"In which country is Angkor Wat?","c":["Thailand","Vietnam","Cambodia","Laos"]}$$::jsonb),
  (46, $${"q":"In which of the following countries is English NOT an official/working language?","c":["Singapore","Philippines","Indonesia","India"]}$$::jsonb),
  (47, $${"q":"Which national flag features a star and a crescent moon together?","c":["Turkiye","Japan","Korea","Greece"]}$$::jsonb),
  (48, $${"q":"Which national flag features a red sun disc?","c":["Japan","UK","USA","Germany"]}$$::jsonb),
  (49, $${"q":"Which is the correct color order of the Russian flag?","c":["White-Blue-Red","Red-Yellow-Blue","Black-Yellow-Red","Blue-Yellow-Red"]}$$::jsonb),
  (50, $${"q":"What is the currency of Chile?","c":["Peso","Real","Sol","Bolivar"]}$$::jsonb),
  (51, $${"q":"What is the currency of India?","c":["Rupee","Dinar","Yuan","Peso"]}$$::jsonb),
  (52, $${"q":"What is the currency of Vietnam?","c":["Dong (VND)","Baht","Peso","Rupee"]}$$::jsonb),
  (53, $${"q":"What is the currency of Switzerland?","c":["Euro","Franc (CHF)","Mark","Krone"]}$$::jsonb),
  (54, $${"q":"Paella originates from which country?","c":["Italy","Spain","Portugal","Mexico"]}$$::jsonb),
  (55, $${"q":"Pho (rice noodle soup) is most famously from which country?","c":["China","Thailand","Vietnam","Laos"]}$$::jsonb),
  (56, $${"q":"With which city is dim sum culture most associated?","c":["Hong Kong","Tokyo","Seoul","Singapore"]}$$::jsonb),
  (57, $${"q":"Which country has the largest Hindu population?","c":["Thailand","India","Indonesia","Nepal"]}$$::jsonb),
  (58, $${"q":"Which religion is followed by the majority in Saudi Arabia?","c":["Buddhism","Islam","Christianity","Hinduism"]}$$::jsonb),
  (59, $${"q":"What is the state religion of Vatican City?","c":["Orthodox","Catholicism","Protestantism","Islam"]}$$::jsonb),
  (60, $${"q":"Which religion is followed by the majority in Bhutan?","c":["Buddhism","Hinduism","Islam","Sikhism"]}$$::jsonb),
  (61, $${"q":"Which African country has the largest population?","c":["Egypt","South Africa","Nigeria","Kenya"]}$$::jsonb),
  (62, $${"q":"Which of the following is NOT one of the Nordic countries?","c":["Norway","Sweden","Finland","Estonia"]}$$::jsonb),
  (63, $${"q":"On which continent is the Sahara Desert?","c":["Asia","Africa","Australia","South America"]}$$::jsonb),
  (64, $${"q":"Through which continent does the Amazon River flow?","c":["North America","South America","Africa","Asia"]}$$::jsonb),
  (65, $${"q":"The Dead Sea lies between which two countries?","c":["Egypt-Sudan","Israel-Jordan","Saudi Arabia-Iraq","Syria-Turkiye"]}$$::jsonb),
  (66, $${"q":"To which country do the Galapagos Islands belong?","c":["Peru","Chile","Ecuador","Colombia"]}$$::jsonb),
  (67, $${"q":"Which of the following is LEAST associated with Viking heritage?","c":["Norway","Sweden","Denmark","Poland"]}$$::jsonb),
  (68, $${"q":"In which present-day country did the 1986 Chernobyl disaster occur?","c":["Russia","Ukraine","Belarus","Poland"]}$$::jsonb),
  (69, $${"q":"In which country was the Berlin Wall?","c":["Germany","Poland","Hungary","Czech Republic"]}$$::jsonb),
  (70, $${"q":"In which of the following countries do cars NOT drive on the left?","c":["Japan","UK","Australia","Germany"]}$$::jsonb),
  (71, $${"q":"Which EU member state does NOT use the euro?","c":["Sweden","Spain","Slovenia","Slovakia"]}$$::jsonb),
  (72, $${"q":"Through which of the following countries does the Equator NOT pass?","c":["Ecuador","Kenya","Indonesia","Peru"]}$$::jsonb),
  (73, $${"q":"Which city straddles two continents (Europe and Asia)?","c":["Istanbul","Moscow","Cairo","Athens"]}$$::jsonb),
  (74, $${"q":"What is the smallest country in the world by land area?","c":["Monaco","San Marino","Vatican City","Liechtenstein"]}$$::jsonb),
  (75, $${"q":"Mount Everest sits on the border between which two countries?","c":["China-India","China-Nepal","India-Nepal","China-Bhutan"]}$$::jsonb),
  (76, $${"q":"As of 2024, which country has the largest population?","c":["China","India","USA","Indonesia"]}$$::jsonb),
  (77, $${"q":"Which small European country is well known for an extremely high GDP per capita?","c":["Luxembourg","South Korea","Japan","France"]}$$::jsonb),
  (78, $${"q":"In which of the following countries are Chinese characters (Hanzi) NOT used as an official script?","c":["China","Taiwan","Japan","Vietnam"]}$$::jsonb),
  (79, $${"q":"Which country uses the Cyrillic alphabet officially?","c":["Poland","Czech Republic","Russia","Hungary"]}$$::jsonb),
  (80, $${"q":"In which of the following countries is Arabic NOT an official language?","c":["Egypt","Iran","Saudi Arabia","Morocco"]}$$::jsonb),
  (81, $${"q":"Which of the following is NOT a constitutional monarchy?","c":["UK","Japan","Sweden","Germany"]}$$::jsonb),
  (82, $${"q":"Which of the following is NOT a NATO member?","c":["Norway","Poland","Switzerland","Canada"]}$$::jsonb),
  (83, $${"q":"Which of the following is NOT a member of OPEC?","c":["Saudi Arabia","Iran","Russia","Venezuela"]}$$::jsonb),
  (84, $${"q":"Where is the aurora borealis LEAST likely to be seen?","c":["Iceland","Finland","Canada","Mexico"]}$$::jsonb),
  (85, $${"q":"On which island country are baobab trees especially iconic?","c":["Madagascar","Mauritius","Seychelles","Comoros"]}$$::jsonb),
  (86, $${"q":"Which national flag has the Arabic Shahada written across the centre?","c":["Saudi Arabia","Iran","Iraq","Egypt"]}$$::jsonb),
  (87, $${"q":"Which country has the most time zones within its single territory?","c":["Russia","USA","Canada","Australia"]}$$::jsonb),
  (88, $${"q":"Dubai is part of which country?","c":["Saudi Arabia","Qatar","United Arab Emirates","Kuwait"]}$$::jsonb),
  (89, $${"q":"In which country is the headquarters of Airbus?","c":["Germany","France","UK","Spain"]}$$::jsonb),
  (90, $${"q":"Through which city does the Prime Meridian (UTC 0) pass?","c":["Paris","London","Berlin","Lisbon"]}$$::jsonb),
  (91, $${"q":"In which city is the NATO headquarters?","c":["Brussels","Paris","London","Washington D.C."]}$$::jsonb),
  (92, $${"q":"In which city is the headquarters of the United Nations?","c":["Washington D.C.","New York","Geneva","Vienna"]}$$::jsonb),
  (93, $${"q":"Which of the following is NOT a Caribbean island country?","c":["Cuba","Jamaica","Costa Rica","Dominican Republic"]}$$::jsonb),
  (94, $${"q":"Which of the following is NOT located in the Balkans?","c":["Serbia","Croatia","Albania","Hungary"]}$$::jsonb),
  (95, $${"q":"In which country is the Andalusia region?","c":["Italy","Spain","Portugal","Greece"]}$$::jsonb),
  (96, $${"q":"In northern Europe, when are auroras hardest to observe?","c":["December","January","June","November"]}$$::jsonb),
  (97, $${"q":"Which of the following is a landlocked country?","c":["Austria","Italy","Croatia","Slovenia"]}$$::jsonb),
  (98, $${"q":"Which of the following is NOT in the Schengen Area?","c":["Germany","France","Ireland","Spain"]}$$::jsonb),
  (99, $${"q":"Which river is most commonly cited as the longest in the world?","c":["Nile","Amazon","Yangtze","Mississippi"]}$$::jsonb),
  (100, $${"q":"Which of the following is a city-state in Southeast Asia?","c":["Thailand","Singapore","Malaysia","Indonesia"]}$$::jsonb)
)
update public.travel_trivia_questions q
set translations = q.translations || jsonb_build_object('en', d.t)
from d
where q.id = d.i;

-- ============================================================
-- 3) UPDATE: ja
-- ============================================================
with d(i,t) as (values
  (1, $${"q":"自由の女神像があるのはどの都市?","c":["ニューヨーク","ワシントンD.C.","ボストン","ロサンゼルス"]}$$::jsonb),
  (2, $${"q":"エッフェル塔があるのはどの都市?","c":["ロンドン","パリ","ローマ","ベルリン"]}$$::jsonb),
  (3, $${"q":"日本の首都は?","c":["大阪","京都","東京","福岡"]}$$::jsonb),
  (4, $${"q":"イギリスの首都は?","c":["エディンバラ","ダブリン","ロンドン","カーディフ"]}$$::jsonb),
  (5, $${"q":"万里の長城があるのはどの国?","c":["日本","韓国","中国","ベトナム"]}$$::jsonb),
  (6, $${"q":"シドニー・オペラハウスがあるのはどの国?","c":["オーストラリア","ニュージーランド","イギリス","カナダ"]}$$::jsonb),
  (7, $${"q":"コロッセオがあるのはどの都市?","c":["ミラノ","ローマ","ヴェネツィア","フィレンツェ"]}$$::jsonb),
  (8, $${"q":"ピラミッドとスフィンクスで最も有名な国は?","c":["メキシコ","エジプト","ペルー","ギリシャ"]}$$::jsonb),
  (9, $${"q":"タイの首都は?","c":["バンコク","チェンマイ","プーケット","パタヤ"]}$$::jsonb),
  (10, $${"q":"アメリカ合衆国の首都は?","c":["ニューヨーク","ロサンゼルス","ワシントンD.C.","シカゴ"]}$$::jsonb),
  (11, $${"q":"カナダ国旗の中央に描かれている葉は?","c":["オークの葉","メープルの葉","イチョウの葉","松の葉"]}$$::jsonb),
  (12, $${"q":"次のうち島国ではないのは?","c":["日本","ニュージーランド","イギリス","ベトナム"]}$$::jsonb),
  (13, $${"q":"キムチとビビンバの本場の国は?","c":["中国","日本","ベトナム","韓国"]}$$::jsonb),
  (14, $${"q":"寿司はどの国の代表料理?","c":["中国","日本","韓国","ベトナム"]}$$::jsonb),
  (15, $${"q":"ピザの本場として最も知られる国は?","c":["ギリシャ","イタリア","フランス","スペイン"]}$$::jsonb),
  (16, $${"q":"バゲットで有名な国は?","c":["イタリア","フランス","ドイツ","イギリス"]}$$::jsonb),
  (17, $${"q":"パスタの本場として知られる国は?","c":["ギリシャ","イタリア","スペイン","ポルトガル"]}$$::jsonb),
  (18, $${"q":"カレーと最も関連が深い国は?","c":["タイ","インド","ベトナム","日本"]}$$::jsonb),
  (19, $${"q":"次のうち英語が主要言語ではない国は?","c":["カナダ","オーストラリア","ニュージーランド","ブラジル"]}$$::jsonb),
  (20, $${"q":"次のうちスペイン語が主要言語ではない国は?","c":["メキシコ","アルゼンチン","ブラジル","チリ"]}$$::jsonb),
  (21, $${"q":"次のうちフランス語を公用語とする国は?","c":["オランダ","フランス","ポーランド","ハンガリー"]}$$::jsonb),
  (22, $${"q":"次のうちドイツ語が公用語ではない国は?","c":["ドイツ","オーストリア","スイス","ポーランド"]}$$::jsonb),
  (23, $${"q":"世界四大文明に含まれないのは?","c":["メソポタミア","エジプト","インダス","ギリシャ"]}$$::jsonb),
  (24, $${"q":"次のうちヨーロッパにある国は?","c":["タイ","ベトナム","ギリシャ","チリ"]}$$::jsonb),
  (25, $${"q":"次のうちアフリカ大陸にある国は?","c":["イラン","エジプト","インド","インドネシア"]}$$::jsonb),
  (26, $${"q":"次のうち南米にある国は?","c":["メキシコ","ブラジル","キューバ","ジャマイカ"]}$$::jsonb),
  (27, $${"q":"カンガルーを象徴とする国は?","c":["ニュージーランド","オーストラリア","南アフリカ","ブラジル"]}$$::jsonb),
  (28, $${"q":"パンダを象徴とする国は?","c":["韓国","中国","日本","タイ"]}$$::jsonb),
  (29, $${"q":"リオのカーニバルで有名な国は?","c":["ブラジル","アルゼンチン","チリ","ペルー"]}$$::jsonb),
  (30, $${"q":"イギリスの通貨単位は?","c":["ユーロ","ポンド","ドル","フラン"]}$$::jsonb),
  (31, $${"q":"アメリカ合衆国の通貨単位は?","c":["ポンド","ユーロ","ドル","円"]}$$::jsonb),
  (32, $${"q":"日本の通貨単位は?","c":["円","元","ウォン","ドン"]}$$::jsonb),
  (33, $${"q":"FIFAワールドカップ最多優勝国は?","c":["ドイツ","イタリア","ブラジル","アルゼンチン"]}$$::jsonb),
  (34, $${"q":"次のうちアルプス山脈が通らない国は?","c":["スイス","イタリア","オーストリア","オランダ"]}$$::jsonb),
  (35, $${"q":"ビッグ・ベンがあるのはどの都市?","c":["パリ","ロンドン","ベルリン","マドリード"]}$$::jsonb),
  (36, $${"q":"オーストラリアの首都は?","c":["シドニー","メルボルン","キャンベラ","ブリスベン"]}$$::jsonb),
  (37, $${"q":"カナダの首都は?","c":["トロント","バンクーバー","オタワ","モントリオール"]}$$::jsonb),
  (38, $${"q":"ブラジルの首都は?","c":["サンパウロ","リオデジャネイロ","ブラジリア","サルバドール"]}$$::jsonb),
  (39, $${"q":"トルコ(テュルキエ)の首都は?","c":["イスタンブール","アンカラ","イズミル","アンタルヤ"]}$$::jsonb),
  (40, $${"q":"南アフリカ共和国の行政首都は?","c":["ヨハネスブルク","ケープタウン","プレトリア","ダーバン"]}$$::jsonb),
  (41, $${"q":"ノルウェーの首都は?","c":["オスロ","ベルゲン","コペンハーゲン","ヘルシンキ"]}$$::jsonb),
  (42, $${"q":"タージ・マハルがあるインドの都市は?","c":["デリー","ムンバイ","アーグラ","ジャイプル"]}$$::jsonb),
  (43, $${"q":"映画「インディ・ジョーンズ」に登場するペトラ遺跡がある国は?","c":["エジプト","ヨルダン","イスラエル","トルコ"]}$$::jsonb),
  (44, $${"q":"インカの空中都市マチュ・ピチュがある国は?","c":["メキシコ","ペルー","チリ","ボリビア"]}$$::jsonb),
  (45, $${"q":"アンコール・ワットがある国は?","c":["タイ","ベトナム","カンボジア","ラオス"]}$$::jsonb),
  (46, $${"q":"次のうち英語が公用語ではない国は?","c":["シンガポール","フィリピン","インドネシア","インド"]}$$::jsonb),
  (47, $${"q":"国旗に星と三日月が描かれている国は?","c":["トルコ","日本","韓国","ギリシャ"]}$$::jsonb),
  (48, $${"q":"国旗に赤い太陽の丸が描かれている国は?","c":["日本","イギリス","アメリカ","ドイツ"]}$$::jsonb),
  (49, $${"q":"ロシア国旗の正しい色の組み合わせは?","c":["白・青・赤","赤・黄・青","黒・黄・赤","青・黄・赤"]}$$::jsonb),
  (50, $${"q":"チリの通貨単位は?","c":["ペソ","レアル","ソル","ボリバル"]}$$::jsonb),
  (51, $${"q":"インドの通貨単位は?","c":["ルピー","ディナール","元","ペソ"]}$$::jsonb),
  (52, $${"q":"ベトナムの通貨単位は?","c":["ドン(VND)","バーツ","ペソ","ルピー"]}$$::jsonb),
  (53, $${"q":"スイスの通貨単位は?","c":["ユーロ","フラン(CHF)","マルク","クローネ"]}$$::jsonb),
  (54, $${"q":"パエリアが生まれた国は?","c":["イタリア","スペイン","ポルトガル","メキシコ"]}$$::jsonb),
  (55, $${"q":"フォー(米麺)で最も有名な国は?","c":["中国","タイ","ベトナム","ラオス"]}$$::jsonb),
  (56, $${"q":"点心(飲茶)文化が最も発達した都市は?","c":["香港","東京","ソウル","シンガポール"]}$$::jsonb),
  (57, $${"q":"ヒンドゥー教徒が最も多い国は?","c":["タイ","インド","インドネシア","ネパール"]}$$::jsonb),
  (58, $${"q":"サウジアラビアで最も信仰されている宗教は?","c":["仏教","イスラム教","キリスト教","ヒンドゥー教"]}$$::jsonb),
  (59, $${"q":"バチカン市国の国教は?","c":["正教会","カトリック","プロテスタント","イスラム教"]}$$::jsonb),
  (60, $${"q":"ブータンで最も信仰されている宗教は?","c":["仏教","ヒンドゥー教","イスラム教","シク教"]}$$::jsonb),
  (61, $${"q":"アフリカで人口が最も多い国は?","c":["エジプト","南アフリカ","ナイジェリア","ケニア"]}$$::jsonb),
  (62, $${"q":"次のうち北欧5か国(Nordic)に含まれない国は?","c":["ノルウェー","スウェーデン","フィンランド","エストニア"]}$$::jsonb),
  (63, $${"q":"サハラ砂漠があるのはどの大陸?","c":["アジア","アフリカ","オーストラリア","南米"]}$$::jsonb),
  (64, $${"q":"アマゾン川が流れる大陸は?","c":["北米","南米","アフリカ","アジア"]}$$::jsonb),
  (65, $${"q":"死海と国境を接する2か国は?","c":["エジプト-スーダン","イスラエル-ヨルダン","サウジ-イラク","シリア-トルコ"]}$$::jsonb),
  (66, $${"q":"ガラパゴス諸島が属する国は?","c":["ペルー","チリ","エクアドル","コロンビア"]}$$::jsonb),
  (67, $${"q":"次のうちヴァイキングの末裔のイメージから最も遠い国は?","c":["ノルウェー","スウェーデン","デンマーク","ポーランド"]}$$::jsonb),
  (68, $${"q":"1986年チェルノブイリ原発事故が起きた現在の国は?","c":["ロシア","ウクライナ","ベラルーシ","ポーランド"]}$$::jsonb),
  (69, $${"q":"ベルリンの壁があった国は?","c":["ドイツ","ポーランド","ハンガリー","チェコ"]}$$::jsonb),
  (70, $${"q":"次のうち左側通行ではない国は?","c":["日本","イギリス","オーストラリア","ドイツ"]}$$::jsonb),
  (71, $${"q":"EU加盟国だがユーロを使用しない国は?","c":["スウェーデン","スペイン","スロベニア","スロバキア"]}$$::jsonb),
  (72, $${"q":"次のうち赤道が通らない国は?","c":["エクアドル","ケニア","インドネシア","ペルー"]}$$::jsonb),
  (73, $${"q":"2大陸(ヨーロッパ-アジア)にまたがる都市は?","c":["イスタンブール","モスクワ","カイロ","アテネ"]}$$::jsonb),
  (74, $${"q":"世界で最も国土面積が小さい国は?","c":["モナコ","サンマリノ","バチカン市国","リヒテンシュタイン"]}$$::jsonb),
  (75, $${"q":"エベレスト山が国境となる2か国は?","c":["中国-インド","中国-ネパール","インド-ネパール","中国-ブータン"]}$$::jsonb),
  (76, $${"q":"2024年時点で人口が最も多い国は?","c":["中国","インド","アメリカ","インドネシア"]}$$::jsonb),
  (77, $${"q":"一人当たりGDPが非常に高いことで知られる欧州の小国は?","c":["ルクセンブルク","韓国","日本","フランス"]}$$::jsonb),
  (78, $${"q":"次のうち漢字を公式文字として使わない国は?","c":["中国","台湾","日本","ベトナム"]}$$::jsonb),
  (79, $${"q":"キリル文字を公式に使用する国は?","c":["ポーランド","チェコ","ロシア","ハンガリー"]}$$::jsonb),
  (80, $${"q":"次のうちアラビア語が公用語ではない国は?","c":["エジプト","イラン","サウジアラビア","モロッコ"]}$$::jsonb),
  (81, $${"q":"次のうち立憲君主制ではない国は?","c":["イギリス","日本","スウェーデン","ドイツ"]}$$::jsonb),
  (82, $${"q":"次のうちNATO加盟国ではない国は?","c":["ノルウェー","ポーランド","スイス","カナダ"]}$$::jsonb),
  (83, $${"q":"次のうちOPEC加盟国ではない国は?","c":["サウジアラビア","イラン","ロシア","ベネズエラ"]}$$::jsonb),
  (84, $${"q":"オーロラ観測に適さない場所は?","c":["アイスランド","フィンランド","カナダ","メキシコ"]}$$::jsonb),
  (85, $${"q":"バオバブの木で有名な島国は?","c":["マダガスカル","モーリシャス","セーシェル","コモロ"]}$$::jsonb),
  (86, $${"q":"国旗の中央にアラビア語の文言(シャハーダ)が書かれている国は?","c":["サウジアラビア","イラン","イラク","エジプト"]}$$::jsonb),
  (87, $${"q":"一つの国の中に最も多くのタイムゾーンがある国は?","c":["ロシア","アメリカ","カナダ","オーストラリア"]}$$::jsonb),
  (88, $${"q":"ドバイが属する国は?","c":["サウジアラビア","カタール","アラブ首長国連邦","クウェート"]}$$::jsonb),
  (89, $${"q":"エアバスの本社がある国は?","c":["ドイツ","フランス","イギリス","スペイン"]}$$::jsonb),
  (90, $${"q":"国際標準時(UTC 0)の基準子午線が通る都市は?","c":["パリ","ロンドン","ベルリン","リスボン"]}$$::jsonb),
  (91, $${"q":"NATO本部がある都市は?","c":["ブリュッセル","パリ","ロンドン","ワシントンD.C."]}$$::jsonb),
  (92, $${"q":"国際連合(UN)本部がある都市は?","c":["ワシントンD.C.","ニューヨーク","ジュネーブ","ウィーン"]}$$::jsonb),
  (93, $${"q":"次のうちカリブ海の島国ではないのは?","c":["キューバ","ジャマイカ","コスタリカ","ドミニカ共和国"]}$$::jsonb),
  (94, $${"q":"次のうちバルカン半島に位置しない国は?","c":["セルビア","クロアチア","アルバニア","ハンガリー"]}$$::jsonb),
  (95, $${"q":"アンダルシア地方がある国は?","c":["イタリア","スペイン","ポルトガル","ギリシャ"]}$$::jsonb),
  (96, $${"q":"北欧でオーロラ観測が最も難しい時期は?","c":["12月","1月","6月","11月"]}$$::jsonb),
  (97, $${"q":"次のうち海に面していない(内陸国)国は?","c":["オーストリア","イタリア","クロアチア","スロベニア"]}$$::jsonb),
  (98, $${"q":"次のうちシェンゲン圏に含まれない国は?","c":["ドイツ","フランス","アイルランド","スペイン"]}$$::jsonb),
  (99, $${"q":"世界一長い川として最も広く知られているのは?","c":["ナイル川","アマゾン川","長江","ミシシッピ川"]}$$::jsonb),
  (100, $${"q":"東南アジアを代表する都市国家(City-state)は?","c":["タイ","シンガポール","マレーシア","インドネシア"]}$$::jsonb)
)
update public.travel_trivia_questions q
set translations = q.translations || jsonb_build_object('ja', d.t)
from d
where q.id = d.i;
